const assert = require('node:assert/strict');
require('../media.js');
const {accessAction,videoSource} = globalThis.SiteMedia;
assert.equal(accessAction({value:'https://www.bilibili.com/video/BV1B7411m7LV/'}).type,'link');
assert.equal(accessAction({platform:'qq',value:'862835994'}).type,'copy');
assert.equal(accessAction({value:'https://example.com',action:'copy'}).type,'copy');
for(const value of ['javascript:alert(1)','https://user:pass@example.com','待发布','展示样例，待替换']) assert.equal(accessAction({value}).type,'unavailable');
assert.equal(accessAction({url:'https://example.com',copyable:false}).type,'unavailable');
assert(videoSource({platform:'bilibili',id:'BV1B7411m7LV'}).embed.startsWith('https://player.bilibili.com/'));
assert(videoSource({platform:'douyin',id:'7146408143612000000',aspectRatio:9/16}).ratio < 1);
assert(videoSource({platform:'youtube',id:'M7lc1UVf-VE'}).embed.startsWith('https://www.youtube.com/embed/'));
assert.equal(videoSource({platform:'youtube',id:'javascript:alert(1)'}),null);
assert.equal(videoSource({platform:'other',id:'123'}),null);
assert.equal(videoSource(undefined),null);
assert.equal(videoSource({platform:'youtube',id:'M7lc1UVf-VE',aspectRatio:'bad'}).ratio,16/9);
console.log('Media data tests passed: video providers, aspect ratios, safe links, copy actions and unavailable entries.');
